apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-production
  labels:
    app: web-app
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: registry.local/web-app-production
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: 256Mi
            cpu: "0.2"
          limits:
            memory: 1024Mi
            cpu: "1"
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: web-app-configmap
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: web-app-configmap
              key: DB_PORT
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: web-app-configmap
              key: PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: web-app-configmap
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: web-app-secrets
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: web-app-secrets
              key: DB_PASS  
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-production
  namespace: production
spec:
  selector:
    app: web-app
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30033
