apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-reports
  namespace: devsecops
spec:
  storageClassName: reports
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-trivy-cache
  namespace: devsecops
spec:
  storageClassName: trivy-cache
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-zap-wrk
  namespace: devsecops
spec:
  storageClassName: zap-wrk
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

