apiVersion: v1
kind: ConfigMap
metadata:
  name: web-app-configmap
data:
  DB_HOST: '10.0.0.20'
  DB_PORT: '5432'
  DB_NAME: 'product'
  PORT: '3000'
---
apiVersion: v1
kind: Secret
metadata:  
  name: web-app-secrets
type: Opaque
data:
  DB_USER: cm9vdA==
  DB_PASS: VGhhb3Z5MjQ=